services:
    pimcore.ecommerceframework.session_configurator:
        class: Pimcore\Bundle\PimcoreEcommerceFrameworkBundle\Tools\SessionConfigurator
        tags:
            - { name: pimcore.session.configurator }
