# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: pimcore

# The runtime the application uses.
type: php:8.1

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'db:mysql'
    rediscache: 'cacheredis:redis'

build:
  flavor: none

# Add additional PHP extensions.
runtime:
  extensions:
    - iconv
    - dom
    - simplexml
    - exif
    - opcache
    - imagick
    - fileinfo

variables:
  php:
      memory_limit: 1024M

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    "/var":
      source: "local"
      source_path: "var"
    "/public":
      source: "local"
      source_path: "public"

# The configuration of app when it is exposed to the web.
web:
  locations:
    '/':
      root: public
      passthru: "/index.php"
      allow: true
      rules:
        '^/videos/(?<resource>.*)$':
          allow: true
        '^/img/(?<resource>.*)$':
          allow: true
        '^/static/(?<resource>.*)$':
          allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e

    bash install-redis.sh 5.1.1

    # This is needed for the installer in the deploy hook.
    curl -fsS https://platform.sh/cli/installer | php

    composer install --no-ansi --no-progress --prefer-dist --no-scripts
  deploy: |
    if [ ! -f var/.platform.installed ]; then
        # These values are for the inital setup only.  You really need to change them
        # after the site is installed.
        export PIMCORE_INSTALL_ADMIN_USERNAME='admin'
        export PIMCORE_INSTALL_ADMIN_PASSWORD='admin'
        ./vendor/bin/pimcore-install --no-interaction --ignore-existing-config --no-debug
        touch var/.platform.installed
    fi

    # Clear env cached
    ./bin/console cache:clear

# The configuration of scheduled execution.
crons:
    pimcore_cron:
        spec: "*/5 * * * *"
        commands:
            start: "bin/console maintenance"

source:
  operations:
    auto-update:
      command: |
        curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0

