# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: pimcore

# The runtime the application uses.
type: php:8.1

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'db:mysql'
    redis: 'redis:redis'

build:
  flavor: none

# Add additional PHP extensions.
# php:8.1: pcntl, zlib not working
runtime:
  extensions:
    - apcu
    - curl
    - dom
    - exif
    - fileinfo
    - gd
    - iconv
    - imagick
    - imap
    - mbstring
    - opcache
    - pdo_mysql
    - redis
    - simplexml
    - zip

variables:
  php:
      memory_limit: 1024M

dependencies:
    php:
        composer/composer: '^2'

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    "/var":
      source: "local"
      source_path: "var"
    "/public/var":
      source: "local"
      source_path: "var-public"

# The configuration of app when it is exposed to the web.
web:
  locations:
    '/':
      root: "public"
      passthru: "/index.php"
      allow: true
      rules:
        '^/videos/(?<resource>.*)$':
          allow: true
        '^/img/(?<resource>.*)$':
          allow: true
        '^/static/(?<resource>.*)$':
          allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e

    # This is needed for the installer in the deploy hook.
    COMPOSER_MEMORY_LIMIT=-1 composer install --no-ansi --no-progress --prefer-dist --no-scripts
  deploy: |
    set -e

    if [ ! -f var/.platform.installed ]; then
        ./vendor/bin/pimcore-install \ 
          --no-interaction --ignore-existing-config --no-debug --skip-database-config\
          --admin-username=admin \
          --admin-password=admin \
          --mysql-host-socket=database.internal \
          --mysql-username=pimcore \
          --mysql-password= \
          --mysql-database=main
        touch var/.platform.installed
    fi

    # Clear env cached
    ./bin/console cache:clear

# The configuration of scheduled execution.
crons:
    pimcore_cron:
        spec: "*/5 * * * *"
        commands:
            start: "bin/console maintenance"


