# .scrutinizer.yml
filter:
    excluded_paths:
        - tests/*
        - build/*
        - plugins_example/*
        - update/*
        - website_demo/*
        - website_example/*
        - pimcore/static/*
        - pimcore/static5/*
        - pimcore/lib/Csv/*
        - pimcore/lib/Google/*
        - pimcore/lib/Hybrid/*
        - pimcore/lib/Net/*
        - pimcore/lib/Sabre/*
        - pimcore/lib/Whoops/*
        - pimcore/lib/Zend/*
        - pimcore/lib/html2text.php
        - pimcore/lib/less.inc.php
        - pimcore/lib/password_compatibility.php
        - pimcore/lib/simple_html_dom.php
        - pimcore/lib/UUID.php
checks:
    php:
        #duplication: false
        #unused_methods: false
        #unused_parameters: false
        #argument_type_checks: false
        #verify_property_names: false
        #method_calls_on_non_object: false
        #fix_doc_comments: false
        #instanceof_class_exists: false
        #catch_class_exists: false
        #assignment_of_null_return: false
        #use_statement_alias_conflict: false
coding_style:
    php: {  }
