services:
    website_demo.areabrick.blockquote:
        class: WebsiteDemoBundle\Area\Blockquote
        parent: pimcore.areabrick.base_templating_brick
        tags:
            - { name: pimcore.areabrick }

    website_demo.language_switcher:
        class: WebsiteDemoBundle\Templating\LanguageSwitcher
        arguments: ['@pimcore.document_service']
