services:
    website_demo.area.brick.blockquote:
        class: WebsiteDemoBundle\Document\Area\Blockquote
        parent: pimcore.area.brick.templating_base
        tags:
            - { name: pimcore.area.brick }

    website_demo.language_switcher:
        class: WebsiteDemoBundle\Templating\LanguageSwitcher
        arguments: ['@pimcore.document_service']
