imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['php', 'twig', 'zend']
    default_locale:  "%locale%"
    php_errors:
        log: true

cmf_routing:
    chain:
        routers_by_id:
            router.default:             100
            cmf_routing.dynamic_router: 200
    dynamic:
        route_provider_service_id: pimcore.router.dynamic_route_provider

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        # avoid fetching and using services from templates if possible
        # this is only here for compatibility/dev reasons and may be removed later
        container: '@service_container'
