imports:
    - { resource: parameters.yml }
    - { resource: "@PimcoreBundle/Resources/config/config_test.yml" }
    - { resource: security.yml }
    - { resource: services.yml }

doctrine:
    dbal:
        connections:
            default:
                url: '%pimcore_test.db.dsn%'
                host: ~
                port: ~
                dbname: ~
                user: ~
                password: ~

parameters:
    pimcore_test.db.dsn: '%env(PIMCORE_TEST_DB_DSN)%'
    env(PIMCORE_TEST_DB_DSN): ~
