_pimcore:
    resource: "@PimcoreBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_fallback:
    resource: "@PimcoreLegacyBundle/Resources/config/routing.yml"

