app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_pimcore_admin:
    resource: "@PimcoreAdminBundle/Resources/config/routing/routing.yml"

_fallback:
    resource: "@PimcoreLegacyBundle/Resources/config/routing/fallback.yml"
