imports:
  - {resource: event_listeners.yml}

services:

    # Example custom templating helper
    #app.templating..helper.foobar:
    #    class: AppBundle\Templating\Helper\Example
    #    tags:
    #        - { name: templating.helper, alias: fooBar }
