framework:
  cache:
    pools:
      pimcore.cache.pool:
        public: true
        tags: true
        default_lifetime: 31536000  # 1 year
        adapter: pimcore.cache.adapter.redis_tag_aware
        provider: 'redis://%redis_host%'
      cache.annotations:
        adapter: pimcore.cache.pool

# define services for database storage determination
services:
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - 'mysql:dbname=%database_name%; host=%database_host%; port=%database_port%'
      - { db_username: '%database_user%', db_password: '%database_password%' }
