services:
    app.templating.language_switcher:
        class: AppBundle\Templating\LanguageSwitcher
        arguments: ['@pimcore.document_service']

    app.templating..helper.foobar:
        class: AppBundle\Templating\Helper\FooBar
        tags:
            - { name: templating.helper, alias: fooBar }
