services:
    pimcore.event_listener.editmode:
        class: PimcoreBundle\EventListener\Editmode
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }



