services:
    pimcore.legacy_kernel:
        class: PimcoreBundle\HttpKernel\LegacyKernel
        arguments: ['@kernel']

    pimcore.plugin_broker:
        class: Pimcore\API\Plugin\Broker

    pimcore.event_listener.editmode:
        class: PimcoreBundle\EventListener\Editmode
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    pimcore.event_listener.areablock:
        class: PimcoreBundle\EventListener\Areablock
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    pimcore.event_listener.zend_translate:
        class: PimcoreBundle\EventListener\ZendTranslate
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    pimcore.zend_view_provider:
        class: PimcoreBundle\View\ZendViewProvider
        arguments: ['@pimcore.legacy_kernel']

    # TODO inject user?
    pimcore.document_service:
        class: Pimcore\Model\Document\Service
