services:
    pimcore.view.zend_view.name_parser:
        class: PimcoreBundle\Templating\ZendTemplateNameParser
        arguments: ['@kernel']

    pimcore.view.zend_view.resolver:
        class: PimcoreBundle\Templating\ZendResolver
        arguments:
            - '@pimcore.view.zend_view.name_parser'
            - '@templating.locator'

    pimcore.view.zend_view.php_renderer:
        class: Zend\View\Renderer\PhpRenderer
        calls:
            - [setResolver, ['@pimcore.view.zend_view.resolver']]

    templating.engine.zend:
        class: PimcoreBundle\Templating\ZendEngine
        arguments:
            - '@pimcore.view.zend_view.php_renderer'
            - '@pimcore.view.zend_view.name_parser'
            - '@templating.loader.filesystem'
        tags:
            - { name: templating.engine }
