services:
    pimcore.templating.zend.helper_service_manager:
        class: Zend\ServiceManager\ServiceManager

    pimcore.templating.zend.helper_plugin_manager:
        class: Zend\View\HelperPluginManager
        arguments: ['@pimcore.templating.zend.helper_service_manager']

    pimcore.templating.zend.php_renderer:
        class: PimcoreBundle\Templating\Zend\PhpRenderer
        calls:
            - [setResolver, ['@pimcore.templating.zend.view_resolver']]
            - [setHelperPluginManager, ['@pimcore.templating.zend.helper_plugin_manager']]
            - [setTagRenderer, ['@pimcore.document.tag.renderer']]

    pimcore.templating.zend.name_parser:
        class: PimcoreBundle\Templating\Zend\ZendTemplateNameParser
        arguments: ['@kernel']

    pimcore.templating.zend.view_resolver:
        class: PimcoreBundle\Templating\Zend\ZendViewResolver
        arguments:
            - '@pimcore.templating.zend.name_parser'
            - '@templating.locator'

    pimcore.templating.zend.view_helper.document_tag:
        class: PimcoreBundle\Templating\Zend\Helper\DocumentTag
        arguments:
            - '@pimcore.document.tag.renderer'
            - '@pimcore.service.request.document_resolver'
        tags:
            - { name: pimcore.zend.view_helper, alias: documentTag }

    templating.engine.zend:
        class: PimcoreBundle\Templating\Zend\ZendEngine
        arguments:
            - '@pimcore.templating.zend.php_renderer'
            - '@pimcore.templating.zend.name_parser'
            - '@templating.loader.filesystem'
        tags:
            - { name: templating.engine }
