services:
    pimcore.document.tag.renderer:
        class: PimcoreBundle\Document\TagRenderer
        arguments: ['@pimcore.zend_view_provider', '@pimcore.service.request.editmode_resolver']
        calls:
            - [setLogger, ['@logger']]

    pimcore.view.zend_view_helper_bridge:
        class: PimcoreBundle\View\ZendViewHelperBridge
        arguments: ['@pimcore.zend_view_provider']
