services:
    pimcore.templating.zend.name_parser:
        class: PimcoreBundle\Templating\Zend\ZendTemplateNameParser
        arguments: ['@kernel']

    pimcore.templating.zend.view_resolver:
        class: PimcoreBundle\Templating\Zend\ZendViewResolver
        arguments:
            - '@pimcore.templating.zend.name_parser'
            - '@templating.locator'

    pimcore.templating.zend.php_renderer:
        class: Zend\View\Renderer\PhpRenderer
        calls:
            - [setResolver, ['@pimcore.templating.zend.view_resolver']]

    templating.engine.zend:
        class: PimcoreBundle\Templating\Zend\ZendEngine
        arguments:
            - '@pimcore.templating.zend.php_renderer'
            - '@pimcore.templating.zend.name_parser'
            - '@templating.loader.filesystem'
        tags:
            - { name: templating.engine }
