services:
    pimcore.twig.document_tag_extension:
        class: PimcoreBundle\Twig\DocumentTagExtension
        arguments: ['@pimcore.document.tag.renderer']
        public: false
        tags:
            - { name: twig.extension }

    pimcore.twig.zend_view_helper_extension:
        class: PimcoreBundle\Twig\ZendViewHelperExtension
        arguments: ['@pimcore.view.zend_view_helper_bridge']
        public: false
        tags:
            - { name: twig.extension }
