imports:
  - {resource: event_listeners.yml}

services:

    # Example custom templating helper
    #app.templating..helper.foobar:
    #    class: AppBundle\Templating\Helper\Example
    #    tags:
    #        - { name: templating.helper, alias: fooBar }

    website_demo.area.brick.blockquote:
        class: AppBundle\Document\Areabrick\Blockquote
        parent: pimcore.area.brick.templating_base
        tags:
            - { name: pimcore.area.brick }

    website_demo.language_switcher:
        class: AppBundle\Templating\LanguageSwitcher
        arguments: ['@pimcore.document_service']
