services:
    pimcore.zend.event_listener.zend_controller:
        class: PimcoreZendBundle\EventListener\ZendControllerListener
        arguments:
            - '@templating'
            - '@pimcore.service.request.template_vars_resolver'
            - '@sensio_framework_extra.view.guesser'
        tags:
            - { name: kernel.event_subscriber }

    pimcore.zend.templating.helper_service_manager:
        class: Zend\ServiceManager\ServiceManager

    pimcore.zend.templating.helper_plugin_manager:
        class: Zend\View\HelperPluginManager
        arguments: ['@pimcore.zend.templating.helper_service_manager']

    pimcore.zend.templating.php_renderer:
        class: PimcoreZendBundle\Templating\Zend\PhpRenderer
        calls:
            - [setResolver, ['@pimcore.zend.templating.view_resolver']]
            - [setHelperPluginManager, ['@pimcore.zend.templating.helper_plugin_manager']]
            - [setZendViewHelperBridge, ['@pimcore.view.zend_view_helper_bridge']]
            - [setTagRenderer, ['@pimcore.document.tag.renderer']]

    pimcore.zend.templating.name_parser:
        class: PimcoreZendBundle\Templating\ZendTemplateNameParser
        arguments: ['@kernel']

    pimcore.zend.templating.view_resolver:
        class: PimcoreZendBundle\Templating\Zend\ZendViewResolver
        arguments:
            - '@pimcore.zend.templating.name_parser'
            - '@templating.locator'

    pimcore.zend.templating.view_helper.global_variables:
        class: PimcoreZendBundle\Templating\Zend\Helper\GlobalVariables
        arguments:
            - '@templating.globals'
        tags:
            - { name: pimcore.zend.view_helper, alias: app }

    pimcore.zend.templating.view_helper.document_tag:
        class: PimcoreZendBundle\Templating\Zend\Helper\DocumentTag
        arguments:
            - '@pimcore.document.tag.renderer'
            - '@pimcore.service.request.document_resolver'
        tags:
            - { name: pimcore.zend.view_helper, alias: documentTag }

    templating.engine.zend:
        class: PimcoreZendBundle\Templating\ZendEngine
        arguments:
            - '@pimcore.zend.templating.php_renderer'
            - '@pimcore.zend.templating.name_parser'
            - '@templating.loader.filesystem'
        tags:
            - { name: templating.engine }
